version: '3.9.6'

services:
  java_app:
    container_name: java_app
    image: adahack64143/ahsokavoice:latest
    build: .
    ports:
      - 8080:8080
    environment:
      database_host: dpg-cq8v22rv2p9s73cb30ag-a
      database_name: ahsokavoice_356l
      database_user: ahsokavoice_356l_user
      database_password: XJ6JiDmOMYugKfWmUEDNJxkfgtC0oWL4
    depends_on:
      - java_db

  java_db:
    container_name: java_db
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: S271994v
      POSTGRES_DB: postgres